export const fontMap: Record<string, string> = {
    Outfit: "'Outfit', sans-serif",
    Lora: "'Lora', serif",
    Lexend: "'Lexend', sans-serif",
    "Instrument Serif": "'Instrument Serif', serif",
    "Caveat (Handwriting)": "'Caveat', cursive",
    "Dancing Script (Handwriting)": "'Dancing Script', cursive",
    "Pacifico (Handwriting)": "'Pacifico', cursive",
    "Darius (Bodoni)": "'Bodoni Moda', serif",
    "Cormorant Garamond": "'Cormorant Garamond', serif",
    "Playfair Display": "'Playfair Display', serif",
    Newsreader: "'Newsreader', serif",
    Cinzel: "'Cinzel', serif",
    Inter: "'Inter', sans-serif",
    Montserrat: "'Montserrat', sans-serif",
    "Space Grotesk": "'Space Grotesk', sans-serif",
    "Plus Jakarta Sans": "'Plus Jakarta Sans', sans-serif",
    Roboto: "'Roboto', sans-serif",
    "Fira Code (Monospace)": "'Fira Code', monospace",
    Orbitron: "'Orbitron', sans-serif",
    VT323: "'VT323', monospace",
    "Google Sans Flex": "'Google Sans Flex Variable', 'Google Sans Flex', 'Google Sans', sans-serif",
    "System Default": "system-ui, -apple-system, sans-serif",
};

export const FONT_OPTIONS = [
    { value: "Outfit", label: "Outfit (Geometric - Default)" },
    { value: "Lora", label: "Lora (Serif)" },
    { value: "Lexend", label: "Lexend (Modern Sans)" },
    { value: "Inter", label: "Inter (Clean Sans)" },
    { value: "Plus Jakarta Sans", label: "Plus Jakarta Sans" },
    { value: "Space Grotesk", label: "Space Grotesk (Tech)" },
    { value: "Montserrat", label: "Montserrat (Geo Sans)" },
    { value: "Roboto", label: "Roboto (Universal Sans)" },
    { value: "Instrument Serif", label: "Instrument Serif (Editorial)" },
    { value: "Darius (Bodoni)", label: "Darius (Bodoni Serif)" },
    { value: "Playfair Display", label: "Playfair Display (Serif)" },
    { value: "Cormorant Garamond", label: "Cormorant Garamond (Serif)" },
    { value: "Newsreader", label: "Newsreader (Book Serif)" },
    { value: "Cinzel", label: "Cinzel (Classic Display)" },
    { value: "Caveat (Handwriting)", label: "Caveat (Handwriting)" },
    {
        value: "Dancing Script (Handwriting)",
        label: "Dancing Script (Handwriting)",
    },
    { value: "Pacifico (Handwriting)", label: "Pacifico (Handwriting)" },
    { value: "Fira Code (Monospace)", label: "Fira Code (Monospace)" },
    { value: "Orbitron", label: "Orbitron (Futuristic)" },
    { value: "VT323", label: "VT323 (Retro Monospace)" },
    { value: "Google Sans Flex", label: "Google Sans Flex (Variable Sans)" },
    { value: "System Default", label: "System Default" },
];

export const FONT_PRESETS = [
    {
        name: "Editorial Elegant (Default)",
        primary: "Outfit",
        secondary: "Lora",
    },
    {
        name: "Modern Minimalist",
        primary: "Inter",
        secondary: "Plus Jakarta Sans",
    },
    {
        name: "Editorial Bodoni",
        primary: "Newsreader",
        secondary: "Darius (Bodoni)",
    },
    {
        name: "Cyberpunk Monospace",
        primary: "Space Grotesk",
        secondary: "Fira Code (Monospace)",
    },
    { name: "Classic Roman", primary: "Montserrat", secondary: "Cinzel" },
    {
        name: "Friendly Handwriting",
        primary: "Lexend",
        secondary: "Caveat (Handwriting)",
    },
];
